from tkinter import *
root=Tk()
root.configure(bg="green")
lbl = Label(text="Calculator",fg="Steel BLUE",bd=10,font=('arial',50,'bold'))
lbl.pack()
lbl1= Label( text="Enter 1 number",fg="red",bd=10,font=('arial',30,'bold'))
lbl1.pack()
txt1=Entry(bd=10,font=('arial',16,'bold'),insertwidth=4,fg="green")
txt1.pack()
lbl2= Label( text="Enter 2 number",fg="red",bd=10,font=('arial',30,'bold'))
lbl2.pack()
txt2=Entry(bd=10,font=('arial',16,'bold'),insertwidth=4,fg="green")
txt2.pack()
resul=Label(text="Result",fg="red",bd=10,font=('arial',30,'bold'))
resul.pack()
result=Entry(bd=10,font=('arial',16,'bold'),insertwidth=4)
result.pack()
def Add():
    j=int(txt1.get())+int(txt2.get())
    result.delete(0,END)
    result.insert(0,j)
def Subtract():
    j=int(txt1.get())-int(txt2.get())
    result.delete(0, END)
    result.insert(0,j)
def Multiply():
    j=int(txt1.get())*int(txt2.get())
    result.delete(0, END)
    result.insert(0,j)
def Divide():
    j=int(txt1.get())/int(txt2.get())
    result.delete(0, END)
    result.insert(0,j)
frame = Frame(root)
frame.pack()
bt=Button(frame,text="+",command=Add,width="9",height="8",relief=SUNKEN,bg="yellow")
bt.pack(side=LEFT)
bt1=Button(frame,text="-",command=Subtract,width="9",height="8",relief=SUNKEN,bg="orange")
bt1.pack(side=RIGHT)
bt=Button(frame,text="/",command=Divide,width="9",height="8",relief=SUNKEN,bg="violet")
bt.pack()
bt=Button(frame,text="*",command=Multiply,width="9",height="8",relief=SUNKEN,bg="powder blue")
bt.pack(side=RIGHT)
root.mainloop()